services:
 gateway:
   build: ./gateway
   ports:
     - "3000:3000" # public port
   env_file:
     - ./gateway/.env.docker
 #  environment:
   #  - USER_SERVICE:http://user-service:3001
   #  - PRODUCT_SERVICE:http://product-service:3002
   #  - AUTH_SERVICE:http://auth-service:3003
   depends_on:
     - user-service
     - product-service
     - auth-service

  
 auth-service:
   build: ./services/Auth-service
           # no ports — internal only
   env_file:
     - ./services/Auth-service/.env.docker

 user-service:
   build: ./services/user-service
           # no ports — internal only
   env_file:
     - ./services/user-service/.env.docker

 product-service:
   build: ./services/product-service
              # no ports — internal only
   env_file:
     - ./services/product-service/.env.docker


